//
//  CBTuningDiagram.h
//
//  Created on Jan 8, 2020.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface CBTuningDiagram : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger {
    CBTuningDiagramResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    CBTuningDiagramResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    CBTuningDiagramResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    CBTuningDiagramResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
} CBTuningDiagramResizingBehavior;

extern CGRect CBTuningDiagramResizingBehaviorApply(CBTuningDiagramResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! guitar-model
+ (void)drawGuitar_vertical;
+ (void)drawGuitar_verticalWithFrame:(CGRect)targetFrame resizing:(CBTuningDiagramResizingBehavior)resizing;


#pragma mark - Canvas Images

//! guitar-model
+ (UIImage *)imageOfGuitar_vertical;


@end
